const StoryActionTypes={
  FETCH_STORIES_IDS_START:'FETCH_STORIES_IDS_START',
  FETCH_STORIES_IDS_SUCCESS:'FETCH_STORIES_IDS_SUCCESS',
  FETCH_STORIES_IDS_FAILURE:'FETCH_STORIES_IDS_FAILURE',
  
  FETCH_STORIES_START:'FETCH_STORIES_START',
  FETCH_STORIES_SUCCESS:'FETCH_STORIES_SUCCESS',
  FETCH_STORIES_FAILURE:'FETCH_STORIES_FAILURE',

  FETCH_STORIES_AUTHOR_START:'FETCH_STORIES_AUTHOR_START',
  FETCH_STORIES_AUTHOR_SUCCESS:'FETCH_STORIES_AUTHOR_SUCCESS',
  FETCH_STORIES_AUTHOR_FAILURE:'FETCH_STORIES_AUTHOR_FAILURE'

}

export default StoryActionTypes;